apiVersion: v1
name: hostport-allocator
version: 0.1.0
appVersion: 0.1.0
description: A Helm chart for Kubernetes
home: https://github.com/rmb938/hostport-allocator
sources:
  - https://github.com/rmb938/hostport-allocator
maintainers:
  - name: rmb938
    email: ryan@belgrave.me
