
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-hostport-rmb938-com-v1alpha1-hostport
  failurePolicy: Fail
  name: mhostport.kb.io
  rules:
  - apiGroups:
    - hostport.rmb938.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hostports
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-hostport-rmb938-com-v1alpha1-hostportclaim
  failurePolicy: Fail
  name: mhostportclaim.kb.io
  rules:
  - apiGroups:
    - hostport.rmb938.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hostportclaims
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-hostport-rmb938-com-v1alpha1-hostportclass
  failurePolicy: Fail
  name: mhostportclass.kb.io
  rules:
  - apiGroups:
    - hostport.rmb938.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hostportclasses
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-hostport-rmb938-com-v1alpha1-hostportpool
  failurePolicy: Fail
  name: mhostportpool.kb.io
  rules:
  - apiGroups:
    - hostport.rmb938.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hostportpools

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-hostport-rmb938-com-v1alpha1-hostport
  failurePolicy: Fail
  name: vhostport.kb.io
  rules:
  - apiGroups:
    - hostport.rmb938.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hostports
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-hostport-rmb938-com-v1alpha1-hostportclaim
  failurePolicy: Fail
  name: vhostportclaim.kb.io
  rules:
  - apiGroups:
    - hostport.rmb938.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hostportclaims
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-hostport-rmb938-com-v1alpha1-hostportclass
  failurePolicy: Fail
  name: vhostportclass.kb.io
  rules:
  - apiGroups:
    - hostport.rmb938.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hostportclasses
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-hostport-rmb938-com-v1alpha1-hostportpool
  failurePolicy: Fail
  name: vhostportpool.kb.io
  rules:
  - apiGroups:
    - hostport.rmb938.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hostportpools
