# permissions for end users to edit hostportpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostportpool-editor-role
rules:
- apiGroups:
  - hostport.rmb938.com
  resources:
  - hostportpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hostport.rmb938.com
  resources:
  - hostportpools/status
  verbs:
  - get
