# permissions for end users to view hostportpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostportpool-viewer-role
rules:
- apiGroups:
  - hostport.rmb938.com
  resources:
  - hostportpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hostport.rmb938.com
  resources:
  - hostportpools/status
  verbs:
  - get
