# permissions for end users to view hostportclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostportclasses-viewer-role
rules:
  - apiGroups:
      - hostport.rmb938.com
    resources:
      - hostportclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - hostport.rmb938.com
    resources:
      - hostportclasses/status
    verbs:
      - get
