# permissions for end users to edit hostportallocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostportallocation-editor-role
rules:
- apiGroups:
  - hostport.rmb938.com
  resources:
  - hostportallocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hostport.rmb938.com
  resources:
  - hostportallocations/status
  verbs:
  - get
