# permissions for end users to view hostportclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostportclaim-viewer-role
rules:
- apiGroups:
  - hostport.rmb938.com
  resources:
  - hostportclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hostport.rmb938.com
  resources:
  - hostportclaims/status
  verbs:
  - get
