# permissions for end users to edit hostports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostport-editor-role
rules:
- apiGroups:
  - hostport.rmb938.com
  resources:
  - hostports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hostport.rmb938.com
  resources:
  - hostports/status
  verbs:
  - get
