# permissions for end users to edit hostportclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostportclaim-editor-role
rules:
- apiGroups:
  - hostport.rmb938.com
  resources:
  - hostportclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hostport.rmb938.com
  resources:
  - hostportclaims/status
  verbs:
  - get
