# permissions for end users to view hostports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostport-viewer-role
rules:
- apiGroups:
  - hostport.rmb938.com
  resources:
  - hostports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hostport.rmb938.com
  resources:
  - hostports/status
  verbs:
  - get
