apiVersion: hostport.rmb938.com/v1alpha1
kind: HostPortClaim
metadata:
  name: echo-web
  namespace: sample
spec:
  hostPortClassName: sample
---
apiVersion: v1
kind: Pod
metadata:
  name: echo
  namespace: sample
  annotations:
    claim.hostport.rmb938.com/web: echo-web
spec:
  containers:
    - name: echo
      image: k8s.gcr.io/echoserver:1.4
      ports:
        - name: web
          containerPort: 8080
      env:
        - name: MY_HOST_PORT
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['port.hostport.rmb938.com/web']
