{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hostport-allocator.fullname" . }}
  labels:
    {{- include "hostport-allocator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - hostport.rmb938.com
    resources:
      - hostportclaims
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - hostport.rmb938.com
    resources:
      - hostportclaims/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - hostport.rmb938.com
    resources:
      - hostportclasses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - hostport.rmb938.com
    resources:
      - hostportclasses/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - hostport.rmb938.com
    resources:
      - hostports
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - hostport.rmb938.com
    resources:
      - hostports/status
    verbs:
      - get
      - patch
      - update
  {{- end }}
