{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hostport-allocator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hostport-allocator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hostport-allocator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hostport-allocator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
