apiVersion: v1
kind: Service
metadata:
  name: {{ include "hostport-allocator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hostport-allocator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "hostport-allocator.selectorLabels" . | nindent 4 }}
