name: Build

on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.6'

      - name: Build Manager
        run: |
          make manager

      - name: Build Docker Image
        run: |
          make docker
