name: Helm List and Test

on:
  - push
  - pull_request

jobs:
  lint-test:

    name: Helm Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Install Cert Manager
        run: |
          kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v0.15.2/cert-manager.yaml
          kubectl wait -n cert-manager --for=condition=Available --timeout=300s deployment cert-manager-webhook

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install
          config: ct.yaml
