name: Helm List and Test

on:
  - push
  - pull_request

jobs:
  lint-test:

    name: Helm Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install
          config: ct.yaml
