name: Build

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.22.5"

      - name: Build Manager
        run: |
          make manager

      - name: Build Docker Image
        run: |
          make docker
