name: Helm Lint

on: pull_request

jobs:
  lint:
    name: Helm Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch history
        run: git fetch --prune --unshallow

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.22.5"

      - name: Generate helm CRDs
        run: |
          make helm-crds

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v2.6.1
        with:
          command: lint
          config: ct.yaml
