name: Push Master

on:
  push:
    tags:
      - *

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.6'

      - name: Build Manager
        run: |
          make manager

      - name: Build Docker Image
        env:
          DOCKER_USERNAME: ${{ github.repository_owner }}
          TAG: ${{ github.ref }}
        run: |
          make DOCKER_REPO=ghcr.io/$DOCKER_USERNAME DOCKER_IMAGE_TAG=$TAG docker

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Publish Docker Image
        env:
          DOCKER_USERNAME: ${{ github.repository_owner }}
          TAG: ${{ github.ref }}
        run: |
          make DOCKER_REPO=ghcr.io/$DOCKER_USERNAME DOCKER_IMAGE_TAG=$TAG docker-push
